### ISSUE TITLE
Comment box background color reverted to white

### ISSUE THREAD

**Issue by Shteevie** [dtinth/dark-facebook#52]
![fb color mess](https://cloud.githubusercontent.com/assets/8926247/4417651/d17e1da2-4556-11e4-8200-2101e74ffab0.png)
This may have happened with the recent update to FF. The background color of the comment fields is white, but the text is still light grey, making it impossible to read as you type.

**Comment by SteveJones313** [comment]
This is happening to me as well.

**Comment by dtinth** [comment]
Hello!

What pages are you getting this? It is working fine here. Maybe I will have
to wait a bit until the new CSS gets rolled to me.

Thank you!

**Comment by Shteevie** [comment]
This is happening in my main news feed.
-Steve

On Saturday, September 27, 2014, Thai Pangsakulyanont <
notifications@github.com> wrote:

> Hello!
> 
> What pages are you getting this? It is working fine here. Maybe I will
> have
> to wait a bit until the new CSS gets rolled to me.
> 
> Thank you!
> 
> On Sat, Sep 27, 2014 at 11:23 AM, SteveJones313 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > This is happening to me as well.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/dtinth/dark-facebook/issues/52#issuecomment-57041960.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dtinth/dark-facebook/issues/52#issuecomment-57043429.

## 

Thanks,
Shteevie McLaughlin

**Comment by Overcon** [comment]
This happened to me as well. One day my setup was running fine (I love this theme) and the next I lost the ability to TAB-ENTER to finish a comment. When I lost that ability the box reverted to white and with the white text I cannot read my own comments. Nothing I have done resolves the issue so I had to use another Theme. 

The issue with the Tab-Enter is apparently a bug with SSF and Facebook, but the White text box is not. Where can I modify the theme to make the comment text a different color? Like Bright Red (because the pages I manage are working fine, just my main page and other peoples pages are the comment boxes white).

That way I can continue to use the Theme, but have my comment text a different color until this issue reverts or resolves itself.

Thanks

**Comment by dtinth** [comment]
Hello,

I would love to be able to fix this issue, but Facebook still does not roll out the new CSS code to my account, so it is still working on my side. As you know, Facebook does a lot of A/B testing and usually rolls things out very gradually. Therefore, only when I get the new CSS code from Facebook, then I can fix this issue.

It'd be great if there were more maintainers on this style, but unfortunately, currently there's only me. If anyone has CSS/LESS knowledge and would like to help, then I would appreciate it!

Thanks for understanding.

**Comment by dtinth** [comment]
I just pushed a new version, but I did not test it (because it already works fine for me). Thanks to Social Fixer's debug mode and Daryl B West in SocialFixerUserSupport group for the debug information, I was able to find out where it needs to be changed.

Please verify if it works or not. If so, please close this issue. Thanks!

**Comment by Shteevie** [comment]
Confirmed to look fine on my end - thanks!

**Comment by Xheralt** [comment]
Am still having this problem with Fixer 12.0 - it is particularly noticeable when I try to "Share" something.  FB's prompt text (which gets overwritten when you start typing) is a light grey color that is invisible against the white background.  If the first thing one does is Copy/paste text, that shows up properly, but if one starts typing at the keyboard, the color of the prompt text gets adopted.  I've spent a lot of time block-highlighting comment text to proofread it after typing blind...
